=== FranMejiasGlez/DAM2/ACAD/PrimerTrimestre/ExamenPrimerTrimestre/MejiasGonzalezFrancisco/xml-resources/jaxb/jaxBinding/asignaturasEsquema.xsd
<?xml version="1.0"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->

<xsd:schema version="1.0"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
            elementFormDefault="qualified">
    <xsd:element name="asignaturas">
        <xsd:complexType>
            <xsd:sequence>  
                <xsd:element name="asignatura" type="TipoAsignatura" maxOccurs="50" minOccurs="1"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>           
  <xsd:complexType name="TipoAlumno">
	<xsd:sequence>
		<xsd:element name="nombre">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:minLength value="1"></xsd:minLength>
					<xsd:maxLength value="15"></xsd:maxLength>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:element>
		<xsd:element name="apellidos">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:minLength value="1"></xsd:minLength>
					<xsd:maxLength value="30"></xsd:maxLength>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:element>
		<xsd:element name="direccion" type="TipoDireccion"/>
	 </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="TipoDireccion">
     <xsd:sequence>
      <xsd:element name="calle"  type="xsd:string"/>
      <xsd:element name="numero">
		<xsd:simpleType>
			<xsd:restriction base="xsd:integer">
				<xsd:pattern value="[0-9]{3}"/>
			</xsd:restriction>
		</xsd:simpleType>
	  </xsd:element>	
      <xsd:element name="poblacion">
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:minLength value="1"></xsd:minLength>
				<xsd:maxLength value="25"></xsd:maxLength>
			</xsd:restriction>
		</xsd:simpleType>
	  </xsd:element>
      <xsd:element name="provincia">
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:minLength value="1"></xsd:minLength>
				<xsd:maxLength value="20"></xsd:maxLength>
			</xsd:restriction>
		</xsd:simpleType>
	  </xsd:element>
      <xsd:element name="codigoPostal">
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:pattern value="[0-9]{5}"/>
			</xsd:restriction>
		</xsd:simpleType>
	  </xsd:element>	  
    </xsd:sequence>
  </xsd:complexType>

  <xsd:simpleType name="TipoCodigo">
    <xsd:restriction base="xsd:integer">
        <xsd:minInclusive value="1"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="TipoPruebas">
    <xsd:sequence>
      <xsd:element name="prueba" minOccurs="1" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="nombrePrueba">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:minLength value="1"></xsd:minLength>
			<xsd:maxLength value="15"></xsd:maxLength>
                    </xsd:restriction>			
                </xsd:simpleType>    
            </xsd:element>
            <xsd:element name="nota">
              <xsd:simpleType>
                <xsd:restriction base="xsd:double">
                  <xsd:minInclusive value="1"/>
                  <xsd:maxExclusive value="10"/>
                </xsd:restriction>
              </xsd:simpleType>
            </xsd:element>
            <xsd:element name="peso">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:integer">
                        <xsd:minInclusive value="1"/>
                        <xsd:maxExclusive value="100"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
			<xsd:element name="tipo">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="op"/>
						<xsd:enumeration value="ob"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>	
	 </xsd:sequence>
        <xsd:attribute name="numero" type="TipoCodigo"/>
       </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="TipoAsignatura">
    <xsd:sequence>
      <xsd:element name="alumno" type="TipoAlumno"/>
      <xsd:element name="fechaAlta" type="xsd:date"/>
      <xsd:element name="pruebas"  type="TipoPruebas"/>
    </xsd:sequence>
   </xsd:complexType>
</xsd:schema>

=== FranMejiasGlez/DAM2/ACAD/PrimerTrimestre/ExamenPrimerTrimestre/SacarLosCodigos/Ficheros/asignaturas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->


<asignaturas
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='asignaturasEsquema.xsd'>
    <asignatura>
        <alumno>
            <nombre>Manuel</nombre>
            <apellidos>González Díaz</apellidos>
            <direccion>
                <calle>Andalucía</calle>
                <numero>023</numero>
                <poblacion>Medina del campo</poblacion>
                <provincia>Cádiz</provincia>
                <codigoPostal>40876</codigoPostal>
            </direccion>
        </alumno>
        <fechaAlta>2015-01-23</fechaAlta>
        <pruebas>
            <prueba numero="5">
                <nombrePrueba>Examen</nombrePrueba>
                <nota>5.7</nota>
                <peso>50</peso>
		<tipo>ob</tipo>
            </prueba>
            <prueba numero="3">
                <nombrePrueba>Práctica</nombrePrueba>
                <nota>8</nota>
                <peso>20</peso>
		<tipo>ob</tipo>				
            </prueba>
            <prueba numero="1">
                <nombrePrueba>Actividad</nombrePrueba>
                <nota>7.8</nota>
                <peso>10</peso>
		<tipo>op</tipo>				
            </prueba>            
        </pruebas>
    </asignatura>
    <asignatura>
        <alumno>
            <nombre>Saray</nombre>
            <apellidos>Alavez Mora</apellidos>
            <direccion>
                <calle>Aurora Boreal</calle>
                <numero>012</numero>
                <poblacion>Mairena del Aljarafe</poblacion>
                <provincia>Sevilla</provincia>
                <codigoPostal>41927</codigoPostal>
            </direccion>
        </alumno>
        <fechaAlta>2015-01-10</fechaAlta>
        <pruebas>
            <prueba numero="2">
                <nombrePrueba>Ejercicio</nombrePrueba>
                <nota>8.6</nota>
                <peso>15</peso>
		<tipo>ob</tipo>
            </prueba>
            <prueba numero="3">
                <nombrePrueba>Práctica</nombrePrueba>
                <nota>4.5</nota>
                <peso>20</peso>
		<tipo>ob</tipo>				
            </prueba>
            <prueba numero="1">
                <nombrePrueba>Actividad</nombrePrueba>
                <nota>6.75</nota>
                <peso>10</peso>
		<tipo>op</tipo>				
            </prueba>            
        </pruebas>
    </asignatura>    
    <asignatura>
        <alumno>
            <nombre>Javier</nombre>
            <apellidos>Soto del Real</apellidos>
            <direccion>
                <calle>Nueva</calle>
                <numero>032</numero>
                <poblacion>San Juan del Aznalfarache</poblacion>
                <provincia>Sevilla</provincia>
                <codigoPostal>41926</codigoPostal>
            </direccion>
        </alumno>
        <fechaAlta>2015-02-02</fechaAlta>
        <pruebas>
            <prueba numero="4">
                <nombrePrueba>Participación</nombrePrueba>
                <nota>6.4</nota>
                <peso>40</peso>
		<tipo>op</tipo>				
            </prueba>
            <prueba numero="2">
                <nombrePrueba>Ejercicio</nombrePrueba>
                <nota>9.2</nota>
                <peso>15</peso>
		<tipo>ob</tipo>			
            </prueba>
        </pruebas>
    </asignatura>   
    <asignatura>
        <alumno>
            <nombre>Nuria</nombre>
            <apellidos>Fuentes Pérez</apellidos>
            <direccion>
                <calle>Isabela</calle>
                <numero>002</numero>
                <poblacion>Sevilla</poblacion>
                <provincia>Sevilla</provincia>
                <codigoPostal>41013</codigoPostal>
            </direccion>
        </alumno>
        <fechaAlta>2015-02-02</fechaAlta>
        <pruebas>
            <prueba numero="1">
                <nombrePrueba>Actividad</nombrePrueba>
                <nota>7.75</nota>
                <peso>10</peso>
		<tipo>op</tipo>					
            </prueba>              
            <prueba numero="4">
                <nombrePrueba>Participación</nombrePrueba>
                <nota>8.4</nota>
                <peso>40</peso>
		<tipo>op</tipo>				
            </prueba>
            <prueba numero="5">
                 <nombrePrueba>Examen</nombrePrueba>
                <nota>8.25</nota>
                <peso>50</peso>
		<tipo>ob</tipo>		
            </prueba>
        </pruebas>
    </asignatura>            
</asignaturas>
